### ISSUE TITLE
Beta 5 - Testing Notes

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#1]
Version Specific Build Notes:

**Comment by DocCyblade** [comment]
Alpha v1 Ready to test

**Comment by DocCyblade** [comment]
@JedMeister  - Hopefully by next week upstream will release 2.1.4 and fix #28 and #29. Once this is done, I am pretty sure we are reaching RC status in two weeks or less. Battle testing will start right before RC is released. Once RC is reached, it will be ready for your review. I see this in about two weeks. Anything I need to do that has not already been done that I am missing right now that I can take care of while waiting for upstream to patch them bugs? Want to get ahead of the game.

**Comment by DocCyblade** [comment]
Beta 4 - Ready

Demo data is complete

**Comment by JedMeister** [comment]
We really should have an appliance checklist... OTTOMH I think you're already on top of it all.

You could start playing with the TKLBAM stuff to make sure everything is being included properly? I have no idea, but I wouldn't imagine that upstream will change that much between now and next version.

**Comment by DocCyblade** [comment]
Closing this opting for new issues instead of one long build notes
