### ISSUE TITLE
Discussion: Demo Data

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#11]
Need to pin down what type of demo data is needed. Currently there the following things that can be added that are blank.
- [x] Metadata - Extra fields types, added to Document Types
- [x] Document types - Meta data is assigned to each type
- [ ] Transformations - Allows transform of the preview (Zoom In/Out Crop Etc)
- [ ] Permissions/Roles/Groups - Permissions are added to Roles / Groups are assigned to Role
- [x] Indexes - Indexes uses meta data to create an auto structure (tree like) for the documents
- [x] Smart links - Create links by linking meta data fields. Documents matching will be auto linked. 
- [x] Tags - Just good ole tags

**Comment by DocCyblade** [comment]
@JedMeister - Thoughts on:
1. What should be in the TKL Doc? 
2. What defaults should we add

**Comment by JedMeister** [comment]
1. My thought is something pretty simple. Maybe a doc with pretty much the info you'd expect on a landing page (aka "tklwebcp")? Or maybe the appliance page (render it to pdf or something?)? I'm pretty open to ideas, but generally IMO less is more. If mayan has an offline manual that might worth including as well?! (Just a random thought).
2. I'd be inclined to lean heavily towards minimalism. I think if it's going to be useful for the significant majority of users, then it's worthy of consideration. If it isn't that hard to remove or has no significant overhead and can be easily ignored then that would add weight. 

Conversely, IMO there may still be a case for some demo "data". Even if it may be irrelevant to some users it can often make new software easier to get a feel for and less intimidating.

**Comment by DocCyblade** [comment]
On your first point, was thinking the exact same thing, and Mayan's docs can be turned into a PDF right on their doc site! As for the second, I agree as well. I was thinking two documents, with enough meta data to show how it works with the two documents. 

TBH that was one of my first issues with Mayan, it's so bare on first install you really don't get to experience the power of the app until you start throwing some data into it. I thought maybe some other Linux type documents in PDF format so that it's not just dummy data but data they may even want to keep on the system.

**Comment by JedMeister** [comment]
I like it. Sounds great. :+1:

**Comment by DocCyblade** [comment]
Demo data and 1st screen has been made, just need to make a database dump file
