### ISSUE TITLE
Running php-fastcgi under supervisord instead of systemd

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#14]
I am having more issues getting the PHP cgi server working under systemd (I still don't like it, give me systemV back) than it took to get mayan actually running. Systemd kept failing to start and troubleshooting systemd is like well one of the more harder things. Anyway, Mayan already uses Supervisord to run it's processes, so I googled and there are people running php-fastcgi and nginx out there. So I gave it a go and well. It just works, and the logging seems to be a bit better.

So with that all said, I have it working great that is all the mayan EDMS and Adminer via Nginx via php-fastcgi being monitored by supervisord. Below is my config files. 

**/etc/supervisor/conf.d/php-fastcgi.conf**

```
[fcgi-program:php-cgi]
command=/usr/bin/php-cgi -q -b /var/run/nginx/php-fastcgi.sock
socket=unix:///var/run/nginx/php-fastcgi.sock
process_name=%(program_name)s
user=www-data
numprocs=1
priority=999
autostart=true
autorestart=true
startsecs=1
startretries=3
exitcodes=0,2
stopsignal=QUIT
stopwaitsecs=10
redirect_stderr=true
stdout_logfile=/var/log/supervisor/php.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
environment=PHP_FCGI_CHILDREN=2,PHP_FCGI_MAX_REQUESTS=1000
```

and 

**/etc/nginx/sites-enabled/adminer**

```
server {

    listen 12322 ssl;
    include /etc/nginx/include/ssl;
    root /usr/share/adminer/adminer/;

    error_log /var/log/nginx/adminer-error.log;
    location / {
        index index.php;
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ .php$ {
        fastcgi_param HTTPS on;
        include /etc/nginx/include/php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /adminer {
        alias /usr/share/adminer/adminer/;
    }

    location /adminer-editor {
        alias /usr/share/adminer/editor/;
    }

    location /externals {
        alias /usr/share/adminer/externals/;
    }

}

```

**/etc/nginx/fastcgi_params**

```

fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

fastcgi_param  HTTP_PROXY         "";

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;

```

**Comment by DocCyblade** [comment]
@JedMeister - Thoughts sir? 

I literally have spent more time trying to get adminer to work than getting Mayan EDMS. Mayan work great! Just pushed the latest to dev

**Comment by DocCyblade** [comment]
As a side note, my supervisors experiment above is here https://github.com/DocCyblade/tkl-mayan-edms/tree/dev-adminer-supervisord

**Comment by DocCyblade** [comment]
This is the only thing to keep from being "Beta 1"

**Comment by JedMeister** [comment]
Yeah, sorry I wasn't more explicit. 

[Mattermost](https://github.com/turnkeylinux-apps/mattermost) should be a good example of what needs doing (and I originally took that from the Nginx appliance). All the files required for fastCGI to run via SystemD are in the overlay:
https://github.com/turnkeylinux-apps/mattermost/blob/master/overlay/etc/default/php-fastcgi
https://github.com/turnkeylinux-apps/mattermost/blob/master/overlay/etc/init.d/php-fastcgi

And here's the Nginx config:
https://github.com/turnkeylinux-apps/mattermost/blob/master/overlay/etc/nginx/fastcgi_params
https://github.com/turnkeylinux-apps/mattermost/blob/master/overlay/etc/nginx/include/php
https://github.com/turnkeylinux-apps/mattermost/blob/master/overlay/etc/nginx/sites-available/adminer

You need to enable it within the conf script like this: 
https://github.com/turnkeylinux-apps/mattermost/blob/master/conf.d/main#L31
Strictly speaking that's the "SysVInit way" but because of the compatibility mode in Debian Jessie it still works (even with SystemD)

Also in case you missed it, there is also a shared Nginx SSL overlay (in common):
https://github.com/turnkeylinux/common/tree/master/overlays/nginx/etc/nginx/include

You know this already, but for completeness, it's sourced here: 
https://github.com/turnkeylinux-apps/mattermost/blob/master/Makefile#L3

**Comment by DocCyblade** [comment]
No worries, I have everything working using supervisord in my other branch. Compared to supervisord, the amount of code I removed vs added seemed to be a lot. 

I will give it another go with systemd, My building spree  has come to a close for a few days, a few more long days a head.

**Comment by JedMeister** [comment]
Actually looks like in my rush to respond, I missed the whole point of this thread. Sorry about that. It was only on reading your latest post that I realised that you are using Supervisord! I read it as SystemD! Not quite sure how that happened?!

TBH I have not heard of Supervisord until now. On face value it seems cool, but I'm not really sure of the problem it's actually solving. Some brief googling suggests that it was written to handle Python programs better on Ubuntu (which used the Upstart init system prior to switching to SystemD). But that was anecdotal, so no doubt there is more to it than that.

It still relies on an init system of some sort (so it's not a replacement init system) and appears to more-or-less duplicate the functionality of any other init system (perhaps closer to SystemD's improved level of control as opposed to SysV's simplicity) although I note that it doesn't handle dependencies like SystemD does. I guess in that sense it adds a layer of simplicity to SystemD (which as you note can be tricky to troubleshoot). My suspicion is that it allows software vendors to more finely tune their process management in an init-system agnostic way, but I'm still not sure if I get it right.

However, I'm generally not convinced that adding additional moving parts makes something better. It's just something else that can break. FWIW I speak from my experiences with NodeJS' `pm2` process manager (which is similar to Supervisord but for NodeJS apps).

You are not the first to complain about SystemD's issues with troubleshooting; Liraz certainly agrees with you (and has some tips [here](https://www.turnkeylinux.org/blog/debugging-systemd-sysv-init-compat)). However, personally I have never had any real issues with SystemD and have generally found it reliable and existing SysV initiscripts "just work". I doubt it makes much difference but I always use the `service NAME start|stop|restart|etc` command.

However, in this specific case it sounds like Mayan actually uses it (and relies on it possibly) so it's inclusion is a no brainer. Personally I'd still be inclined to use an /etc/init.d script as then if we reuse the config (i.e. via common) then it doesn't add an additional dependency (supervisord) and will work everywhere.

That's my 2c worth anyway (probably closer to a dollar! :smile: )

PS hope they don't work you too hard! :smile:

**Comment by DocCyblade** [comment]
Thanks for the time you took to explain. I have used supervisord for PHP applications that need worker scripts to be monitored, as they tend to crash and supervisord makes it easy to do just that. Mayan uses it just for that purpose, watches the worker scripts.

I'll have another go with systemd and see where I end up.

Thanks again

**Comment by DocCyblade** [comment]
Going to try and get systemd to work.
