### ISSUE TITLE
Create screen shots

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#17]

**Comment by DocCyblade** [comment]
@JedMeister - How do you make your screen shots? They looked rounded.

**Comment by DocCyblade** [comment]
Found this too!

https://github.com/turnkeylinux/artwork/blob/master/docs/screenshots.rst

**Comment by JedMeister** [comment]
Sorry I was a bit slow...

Have you done this yet? If so great, leave it like that.

If not then I've been considering changing the screenshot size. IMO they're too small. They look pretty crappy for anything other than display on the appliance page. We can easily downsize them for display on the website, but you can also look at them "zoomed in" if you know what I mean?!

**Comment by DocCyblade** [comment]
@JedMeister I have taken a few but did not do any post image processing. What size you thinking?

**Comment by JedMeister** [comment]
TBH, I'm not sure, but bigger... Perhaps make the template 1024×768 at least?! The initial screenshot may need to be a little bigger too, although it should be close (I currently recommend 1080 x 960).

What do you think? IIRC the current resolution (for the template) is 640x480...

But like I said if you've already done some processing on them, leave it be and just use what you have.

**Comment by DocCyblade** [comment]
@JedMeister - Like you said your doc says 1080x690, I'll process one and post it sad what you think

**Comment by DocCyblade** [comment]
Complete
