### ISSUE TITLE
TKL Welcome PDF - Review

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#32]
@JedMeister - Thoughts of the current welcome page?  Anything to add or remove ?

https://github.com/DocCyblade/tkl-mayan-edms/files/531830/TKL-MayanEDMS-Welcome-Source.docx

**Comment by DocCyblade** [comment]
I added sample users, and just added them to the Message of The Day screen.

**Comment by DocCyblade** [comment]
@JedMeister - Does the welcome page look good to you?

**Comment by JedMeister** [comment]
Looks good to me. I think the formatting may be being a little mangled for me (I use LibreOffice) but essentially it looks fine. If you go for a PDF (or both?) you should be able to avoid that.

**Comment by DocCyblade** [comment]
@JedMeister - yeah it's a PDF, I though that was the PDF link!  See #22 for the PDF link.

**Comment by JedMeister** [comment]
That looks better! :smile:

**Comment by DocCyblade** [comment]
Ok I'll mark that as your "official" approval :-)
