### ISSUE TITLE
Keep user data in /usr/share/mayan-edms

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#34]
Since we are [backing up all of the app](https://github.com/DocCyblade/tkl-mayan-edms/issues/7#issuecomment-252838398) I think it would be best to keep the default data document directory.[ Per the Mayan Docs regarding backup/restore](http://mayan.readthedocs.io/en/v2.1.3/topics/backups.html)  we really just need the documents and database. Putting the data back instead of `/srv/edms-data/`

If I do this, where should the demo-data folder go, as it currently is at `/srv/edms-data/demo-data`

**Comment by DocCyblade** [comment]
@JedMeister - Thoughts on this? This would make backup plan simple, add one directory and exclude cache/pyc files.

**Comment by DocCyblade** [comment]
Also it would be in line with the Mayan upstream documentation as well

**Comment by JedMeister** [comment]
Sounds fine to me.

Perhaps put the demo data in a similar location to the "real" data? Something like `mayan/media/demo-data/`?

**Comment by DocCyblade** [comment]
Complete
