### ISSUE TITLE
Create TKLBAM profile

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#35]
Not sure if I understand the creation of the custom profile. This is how I understand it, correct me if I am wrong. 
1. Since I don't have an "official" build there is no TKLBAM profile for TKLBAM to use. 
2. I must create one from a fresh ISO build using `tklbam-internal create-profile`
3. Once the custom profile is built, I can test TKLBM

If the above is correct, my next question is, where does this profile get stored with build code?

**Comment by DocCyblade** [comment]
@JedMeister - Am I understanding the TKLBAM profile? See above

**Comment by DocCyblade** [comment]
@JedMeister - I got to looking around, and it seems the hooks scripts and the profile [needs to be here](https://github.com/turnkeylinux/tklbam-profiles) instead of the build code. 

With that said should I fork and send a PR when the time comes? Until then I can just create a gist and keep them there until we are ready.

**Comment by DocCyblade** [comment]
@JedMeister - I tried to create a custom backup profile, and ran into issues. It seems it wants an archive. Not sure what it wants. Also, I assume you create the official backup profile, as I don't remember
creating one for Odoo.  

```
root@tkl-mayan-edms ~# echo /usr/share/mayan-edms >mayan.conf 
root@tkl-mayan-edms ~# tklbam-internal create-profile mayan-profile mayan.conf
Custom profile written to mayan-profile
=======================================

# List of backup includes and exclude paths
mayan-profile/dirindex.conf

# Index of file timestamps, ownerships and permissions for paths in dirindex.conf
mayan-profile/dirindex

# List of currently installed packages
mayan-profile/packages
root@tkl-mayan-edms ~# tklbam-init --force-profile=~/mayan-profile/
TurnKey Hub Error: Backup profile archive not found: ~/mayan-profile/
root@tkl-mayan-edms ~# 
```

**Comment by JedMeister** [comment]
As you guessed, we generate the profiles when we build the appliances. If you use [buildtasks](https://github.com/turnkeylinux/buildtasks) to create your test ISO then it will automatically produce the TKLBAM profile archive. `bt-iso` does it as part of it's process but FYI it's actually [bin/generate-tklbam-profile](https://github.com/turnkeylinux/buildtasks/blob/master/bin/generate-tklbam-profile) that creates the archive.

**Comment by DocCyblade** [comment]
@JedMeister - I remember you mentioned these before TBH I forgot, I'll download these and give it a go

**Comment by DocCyblade** [comment]
The only thing that needs backing up will be `/usr/share/mayan-edms` once the official profile is made, we can fine tune it later

**Comment by JedMeister** [comment]
Sounds like a plan!
