### ISSUE TITLE
Put demo data in correct place

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#48]
Not sure where the demo data, the SQL File and the welcome pdf and source should be placed. Currently it is at `/usr/share/tkl-mayan-edms/demo-data` and  `/usr/share/tkl-mayan-edms/docs/`

I thought about putting in all in `/usr/share/mayan-edms/turnkey/` under `sample-data` and `doc`

**Comment by DocCyblade** [comment]
@JedMeister - Your thoughts on the demo/sample data location.

**Comment by JedMeister** [comment]
TBH I'm not really sure. I don't think it really matters, your suggestions seem fair and I'm happy to defer to your preference. The SQL file is only needed at build time so it probably doesn't need it's own special place... 

FWIW I tend to use `/usr/local/src` as the place to overlay bits that are needed at build time and are deleted later. Technically it's for source code but with a little effort you can stretch that definition to cover most things! :smile:

**Comment by DocCyblade** [comment]
See #51 closing this
