### ISSUE TITLE
virtualenv from Debian or PIP

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#49]
Started in #41 wanted to break out and specify ask about virtualenv as this is out of my wheelhouse and wanted to get thoughts on using the standard virtualenv vs using PIP to install it globally

@rosarior in regards to Mayan, and @JedMeister thoughts on it from TurnKey perspective

**Version info:**
The version for [ python-virtualenv in jessie is v1.11.6](https://packages.debian.org/jessie/python/python-virtualenv) (released [3/16/2014](https://github.com/pypa/virtualenv/releases/tag/1.11.6)), also need[ jessie package virtualenv v1.11.6](https://packages.debian.org/jessie/virtualenv) note that this does require python3 See Issue #42 for details

The [current version on PyPi s v1.15.2](https://pypi.python.org/pypi/virtualenv/15.0.3), (released in [8/2016](https://github.com/pypa/virtualenv/releases/tag/15.0.3)) 

[As of the current build](https://github.com/DocCyblade/tkl-mayan-edms/blob/dce8dc101054fc0dd628a00f32802bad0e118741/plan/main#L21) we use the Debian package, prior we have used the newer package both ways seem to work

**Comment by JedMeister** [comment]
Personally, if it works with the Debian package, my inclination would be to use that. However, I'm not the developer, I'm not even a python programmer! So there is likely some detail and context that I'm not seeing. What say you @rosarior?

**Comment by DocCyblade** [comment]
I have tested both ways and both work, and going to lean on the side of the deb packages since that is the pattern for TKL. I can change it pretty easy, but unless @rosarior has something to add that we are missing, I am closing this and using the deb package for now.  @rosarior feel free to respond if you want

**Comment by ghost** [comment]
I'm not aware of anybody managing to get it working using only Debian packages. I'm interested in your results, would make take the possibility of packaging Mayan for Debian much closer to reality.
