### ISSUE TITLE
Testing: Config file missing line

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#57]
Missing `SIGNATURES_GPG_PATH = '/usr/bin/gpg1'`

**Comment by JedMeister** [comment]
Is that a typo? Shouldn't it be `SIGNATURES_GPG_PATH = '/usr/bin/gpg'` ? (i.e. no 1 on the end of the path).

**Comment by DocCyblade** [comment]
Probably, that is what was on the doc site, that changed with 2.1.4

**Comment by JedMeister** [comment]
I'm 99.9999% sure it's a typo! :smile:

**Comment by DocCyblade** [comment]
It would seem that this is not a requirement of Deb, but of Ubuntu.

**Comment by DocCyblade** [comment]
Ref Doc:
https://mayan.readthedocs.io/en/v2.1.5/topics/deploying.html

**Comment by JedMeister** [comment]
Ah ha... that makes sense...
