### ISSUE TITLE
Testing: Stage Folder not working

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#58]
This is how it was setup:

1. Created folder `/srv/upload/stage`
2. Change owner to `www-data`
3. Added folder to sources area in Mayan
4. Uploaded 50 PDF files

Nothing happens. I don't see anything in logs not sure whats going on

**Comment by JedMeister** [comment]
I don't even understand what this is doing (or meant to do) but my comments from the other similar thread probably apply here too?!

**Comment by DocCyblade** [comment]
Not sure if I understand how the "stage folder" even works. I thought it was a target for say a network scanner that can put it's files in this location. But not sure what it's supposed to do. 

[The documentation says](https://mayan.readthedocs.io/en/latest/topics/sources.html):

> Staging folder - Folder where networked attached scanned can save image files. The files in these staging folders are scanned and a preview is generated to help the process of upload.

Not sure how the preview is stored, or how it's access within the webUI.

**Comment by DocCyblade** [comment]
@rosarior - I have been beating Mayan up, and it's been doing well in my battle testing :-) One thing I can't seem to get working or maybe I don't under stand the concept is the Stage Folder. I upload things to this folder, but I don't see anything happening, to be honest I am not sure what I am to be looking at! Not sure if it's a turnkey config issue or I am missing the boat in my thought process.

**Comment by ghost** [comment]
Staging folders are used to interface with multi functional equipment in a generic way. You go to the multi functional machine scan a set of documents, have the MF machine store the scanned documents in the staging folder, go back to the computer where Mayan is running and start uploading the documents to Mayan one by one being able to select different document types or rename the files in the same staging folder upload view. Staging folders and Watch folders behave in a similar fashion, the main difference is that Watch folders are automatic and Staging folders are interactive.

Another example of Staging folder use is when you have multiple people scanning documents in MF machines but only allow one person that examines the scans quality and decides what to upload and what to reject and have re-scanned.

Watch folders can be used when you don't care about the quality of the scans or know they will be good, such as when receiving e-faxes as PDFs.

Example of a Staging folder:
![screenshot from 2016-11-08 18-00-19](https://cloud.githubusercontent.com/assets/413955/20119274/3e9d2a7e-a5de-11e6-92e0-264bd77c9938.png)

**Comment by DocCyblade** [comment]
@rosarior - thanks for explaining. I kinda of thought. I will try and setup a test with the current build. I think it was a permission issue.

**Comment by DocCyblade** [comment]
@rosarior - It was one part not understanding how it worked in the GUI and another part permission issues. Thank you! I have opened #61 to add a default upload folder and user to help ease the setup with permissions.
