### ISSUE TITLE
Testing: Watch Folder - Error

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#59]
This is how it was setup:

1. Created folder `/srv/upload/import`
2. Change owner to `www-data`
3. Added folder to sources area in Mayan as a Watched Folder
4. Uploaded 50 PDF files

I get an error `Error processing source: [Errno 13] Permission denied: '/srv/upload/import'`

**Comment by JedMeister** [comment]
Hmm, that weird?! AFAIK Django should use the www-data user account?! Have you double checked the permissions of the directory (I know you set it, but I suggest you double check)?

Also I'd check the permissions of the files themselves? Perhaps the error message is not quite as explicit as it should be?

As a crude test, you could try setting the directory and all the files to `777`?! It's dirty and as a general rule I never recommend that you do that sort of thing, but it will allow you to troubleshoot whether it is actually a filesystem permissions error or something else going on...

**Comment by DocCyblade** [comment]
It seems the issue was file permissions.

**Comment by DocCyblade** [comment]
#47 - Add to documentation
