### ISSUE TITLE
Create demo data/startup data?

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#8]
By default Mayan is completely blank. Might be useful to add some default document types, and even a PDF doc with some links. (instead of the launch page)

**Comment by DocCyblade** [comment]
@JedMeister - Thought on populating it with some meaningful defaults?  Base install there are no document types etc. Make a PDF with a into to the TKL server (Adminer ports / Webmin etc) and also a copy of the PDF manual for Mayan EDMS, or we leave it as is a blank install.

**Comment by JedMeister** [comment]
Some sensible defaults sounds like a great idea to me! As you know many of the apps have a landing page that gives some basic info (often like you are suggesting), so in this case, providing it as a PDF (or some other doc) makes a ton of sense to me!

**Comment by DocCyblade** [comment]
Sounds good!

**Comment by DocCyblade** [comment]
Will pickup on another issue for specifics on what should be included in the demo data
