### ISSUE TITLE
Build: virtualenv breaks when switching

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-mayan-edms#9]
building breaks when:

`source /usr/share/mayan-edms/bin/activate`

**Comment by DocCyblade** [comment]
@JedMeister - Miss me?  did a quick build and it's crashing at 
(https://github.com/DocCyblade/tkl-mayan-edms/blob/dev/conf.d/main#L24)

It could be that my brain is fried from flipping back to days (I worked 15 12 hour nights). I am sure I am missing something.

```
Successfully installed virtualenv
Cleaning up...
+ cd /usr/share
+ virtualenv mayan-edms
New python executable in /usr/share/mayan-edms/bin/python
Installing setuptools, pip, wheel...done.
+ pwd
/usr/share
+ source /usr/share/mayan-edms/bin/activate
tmp/chroot-script.Iayzzj/main: 24: tmp/chroot-script.Iayzzj/main: source: not found
/usr/share/fab/product.mk:476: recipe for target 'build/stamps/root.patched' failed
make: *** [build/stamps/root.patched] Error 127

```

**Comment by JedMeister** [comment]
I'm pretty sure it's the [shell you are using](https://github.com/DocCyblade/tkl-mayan-edms/blob/dev/conf.d/main#L1). Ensure your conf script uses bash explicitly (i.e. `#!/bin/bash`). `/bin/sh` by default is a symlink to dash (the Debian [Almquist Shell](https://en.wikipedia.org/wiki/Almquist_shell)).

```
$ ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Nov  9  2014 /bin/sh -> dash
```

`source` is a bash built in and isn't supported by the dash shell.

**Comment by DocCyblade** [comment]
Well I feel stupid! That makes sense now because fab-chroot into the build and manually ran it and it worked. Thanks for pointing that out

**Comment by JedMeister** [comment]
Don't feel stupid. Although ignorance gets a bad name, it's essentially just lack of knowledge or understanding and can be easily cured by education. Stupidity on the other hand is vastly worse and has no known cure! I suggest instead that you feel educated and/or enlightened! :stuck_out_tongue_closed_eyes:

**Comment by DocCyblade** [comment]
I feel enlightened :-)

**Comment by DocCyblade** [comment]
Issue resoled by using bash as stated above, however I got other build issues :-)

**Comment by DocCyblade** [comment]
This issue resolved

**Comment by JedMeister** [comment]
> however I got other build issues :-)

Guess you don't yet feel stumped by it/them as I can't see it/them noted anywhere?! :smile:

**Comment by DocCyblade** [comment]
It's built. Now just got to see if it starts and I can take it around the block, and hope it does not fall apart before I get it back in the drive way!
